---
document: feedback-pipeline-workload
version: 1
data:
  name: RHEL 8 ACG lvl 1
  description: "More info: https://access.redhat.com/articles/rhel8-abi-compatibility"
  maintainer: asamalik
  packages:
  - glibc
  - libstdc++
  - libgcc
  - libgomp
  - libatomic
  - elfutils-libelf
  - krb5-libs
  - libxml2
  - libxslt
  - libglvnd-glx
  - libglvnd-egl
  - libglvnd-gles
  - libglvnd-opengl
  - mesa-libGLU
  - pam
  - vulkan-loader
  - zlib
  labels:
  - eln
  - c9s
