---
document: feedback-pipeline-workload
version: 1
data:
  name: Kdump support
  description: Tools necessary to support vmcore dumping and analyzing
  maintainer: sst_kernel_debug
  packages:
  - kexec-tools
  - kdump-anaconda-addon
  - memstrack
  - crash
  - snappy
  labels:
  - eln
  - c9s
