document: feedback-pipeline-unwanted
version: 1
data:
  name: Spice Exclusion List
  description: Spice packages that should not be included.
  maintainer: sst_virtualization_spice

  unwanted_packages:
  - spice-server
  - spice-server-devel
  - spice-html5
  - spice-webdavd
  - libphodav-devel
  - libphodav

  - celt051
  - celt051-devel
  - xorg-x11-drv-qxl

  labels:
  - eln
  - c9s
