document: feedback-pipeline-unwanted
version: 1
data:
  name: Desktop - Blocked packages
  description: Desktop - Packages which should not be in ELN
  maintainer: sst_desktop
  unwanted_packages:
  # Future candidates:
  # - libgnomekbd
  # quvi is disabled as a dependency of Totem in RHEL
  - libquvi-scripts
  - libquvi
  - lua-expat
  - lua-lunit
  - lua-socket
  # Rhythmbox dropped from RHEL 9, Totem could be used to play music files
  - libgpod
  - media-player-info
  - rhythmbox
  # Support for file access for iPhones/iPads dropped from RHEL 9
  - libimobiledevice
  - libplist
  - libusbmuxd
  - usbmuxd
  # Replaced by fwupd
  - fwupdate
  # DLNA support dropped from RHEL 9
  - gssdp
  - gupnp-av
  - gupnp-dlna
  - gupnp-igd
  - gupnp
  - dleyna-connector-dbus
  - dleyna-core
  - dleyna-renderer
  - dleyna-server
  # Replaced by gnome-session-kiosk-session
  - metacity
  # Mouse a11y is now provided by gnome-shell
  - mousetweaks
  - gnome-themes-standard
  # Old mozjs releases, the whole system should use only one mozjs - version 78 currently
  - mozjs52
  - mozjs60
  - mozjs68
  # Old or deprecated or unwanted or unused stuff
  - clutter-gtk
  - clutter-gst3
  - clutter
  - cogl
  - libIDL
  - redhat-menus
  - dbus-c++
  - libcroco
  - enca
  - libchamplain
  - libbluray
  - libdmapsharing
  - libaec
  # Replaced by tracker3
  - tracker
  - tracker-miners
  # Only linhandy1 will be part of RHEL 9
  - libhandy
  labels:
  - eln
  - c9s
