document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Desktop
  description: GNOME Desktop core packages
  maintainer: sst_desktop

  packages:
  # Because of gnome-common
  - autoconf-archive
  - freerdp
  - gdm
  - glib2
  - glib2-doc
  - glib2-static
  - glib2-tests
  - gnome-backgrounds
  - gnome-backgrounds-extras
  - gnome-control-center
  - gnome-color-manager
  - gnome-common
  - gnome-devel-docs
  - gnome-extensions-app
  - gnome-online-miners
  - gnome-remote-desktop
  - gnome-session
  - gnome-shell
  - gnome-shell-extensions
  - gnome-tweaks
  - chrome-gnome-shell
  - low-memory-monitor
  - power-profiles-daemon
  - tracker3
  - uresourced
  - xdg-user-dirs-gtk

  labels:
  - eln
  - c9s

  arch_packages:
    armv7hl:
      - fprintd
      - fprintd-pam
    aarch64:
      - fprintd
      - fprintd-pam
    ppc64le:
      - fprintd
      - fprintd-pam
    x86_64:
      - fprintd
      - fprintd-pam

  package_placeholders:
    redhat-logos:
      srpm: redhat-logos
      description: Red Hat-related icons and pictures
      requires:
        - coreutils
      buildrequires:
        - syslinux-perl
        - netpbm-progs
        - hardlink
    redhat-logos-httpd:
      srpm: redhat-logos
      description: Red Hat-related icons and pictures used by httpd
      requires: []
      buildrequires: []
    redhat-logos-ipa:
      srpm: redhat-logos
      description: Red Hat-related icons and pictures used by IPA
      requires: []
      buildrequires: []
    redhat-backgrounds:
      srpm: redhat-logos
      description: Red Hat-related desktop backgrounds
      requires: []
      buildrequires: []
