document: feedback-pipeline-workload
version: 1
data:
  name: Backup tools from CS system management SST
  description: Packages for backup and restoration of the operating system from CS system management SST
  maintainer: sst_cs_system_management

  packages:
  - amanda
  - amanda-client
  - amanda-libs
  - bacula-storage
  - bacula-libs-sql
  - bacula-common
  - bacula-traymonitor
  - bacula-devel
  - bacula-console-bat
  - bacula-console
  - bacula-client
  - bacula-libs
  - bacula-director
  - bacula-logwatch
  - libisoburn-devel
  - xorriso
  - libisoburn
  - libisoburn-doc

  arch_packages:
    #rear not yet supported on s390x and arm

    x86_64:
    - rear

    ppc64le:
    - rear

  labels:
  - eln
  - c9s
