document: feedback-pipeline-workload
version: 1
data:
  name: redfish-finder
  description: Utility for parsing SMBIOS information and configuring canonical BMC access
  maintainer: jsavitz

  packages:
  - redfish-finder

  labels:
  - c9s

  arch_packages:
    x86_64:
    - redfish-finder
    aarch64:
    - redfish-finder
