document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted packages for Ruby
  description: Packages we do not want to ship for Ruby
  maintainer: sst_cs_apps

  unwanted_source_packages:
  - rubygem-bundler

  unwanted_packages:
  - rubygem-rspec-its
  - rubygem-rspec-its-doc
  - rubypick

  labels:
  - eln
