document: feedback-pipeline-workload
version: 1
data:
  name: SPICE remote display
  description: A remote display system built for virtual environments
  maintainer: sst_virtualization_spice

  packages:
  - spice-glib
  - spice-glib-devel
  - spice-gtk
  - spice-gtk-tools
  - spice-gtk3
  - spice-gtk3-devel
  - spice-gtk3-vala
  - spice-protocol
  - libcacard
  - libcacard-devel
  - libgovirt
  - libgovirt-devel
  - spice-vdagent


  labels:
  - eln
