document: feedback-pipeline-workload
version: 1
data:
  name: Legacy support
  description: Support for legacy SysV services
  maintainer: sst_cs_plumbers

  packages:
  - chkconfig
  - ntsysv
  - initscripts

  labels:
  - eln

  package_placeholders:
    xinetd:
      srpm: xinetd
      description: This package is only provided in RHEL
      requires:
        - libselinux
        - libtirpc
        - setup
        - systemd
      buildrequires:
        - autoconf
        - automake
        - gcc
        - libselinux-devel
        - libtirpc-devel
        - systemd
