document: feedback-pipeline-unwanted
version: 1
data:
  name: Platform Tools Unwanted Packages
  description: Packages that Platform Tool maintains in RHEL 8 but won't in RHEL 9
  maintainer: sst_platform_tools
  labels:
  - eln
  - c9s

  unwanted_packages:
  - cloog
  - cloog-devel
  - cppcheck
  - cppcheck-gui
  - cppcheck-htmlreport
  - cppunit
  - cppunit-devel
  - cppunit-doc
  - tinyxml2
  - tinyxml2-devel
  - dpkg
  - dpkg-devel
  - dselect
  - nasm
  - nasm-rdoff
  - yasm
  - yasm-devel
  # The X11 build may require mcpp. We should try hard to remove this
  # dependency because if we can then we can remove mcpp entirely
  # because nothing else should use it.
  - mcpp
  - mcpp-doc
  - libmcpp
  - libmcpp-devel
  # Remove the temporary compat package for libpthread_nonshared.a.
  - compat-libpthread-nonshared
  # Remove nscd in favour of sssd.
  - nscd
  # Remove jsoncpp and rhash which are not used by cmake.
  - jsoncpp
  - rhash
