document: feedback-pipeline-workload
version: 1
data:
  name: Dependencies from CS System management SST
  description: Dependency only packages from CS System management SST
  maintainer: sst_cs_system_management

  packages:
  - basesystem
  - cdparanoia-libs
  - cdparanoia-devel
  - cdparanoia
  - libusal-devel
  - libusal
  - genisoimage
  - wodim
  - icedax
  - ceres-solver
  - ceres-solver-devel
  - dvd+rw-tools
  - eigen3-devel
  - eigen3-doc
  - gflags
  - gflags-devel
  - glog-devel
  - glog
  - gpgme
  - gpgme-devel
  - qgpgme-devel
  - python3-gpg
  - gpgmepp
  - gpgmepp-devel
  - qgpgme
  - lensfun-devel
  - lensfun
  - leptonica
  - leptonica-devel
  - libburn
  - libburn-devel
  - libcdio-devel
  - libcdio
  - libdvdread
  - libdvdread-devel
  - libieee1284
  - libieee1284-devel
  - libisofs
  - libisofs-devel
  - libsmi
  - libsmi-devel
  - metis-devel
  - metis
  - mpfr-devel
  - mpfr
  - oniguruma
  - oniguruma-devel
  - sparsehash-devel
  - tesseract
  - tesseract-devel

  arch_packages:
    #cdrdao not supported on s390x
    aarch64:
    - cdrdao
    i686:
    - cdrdao
    x86_64:
    - cdrdao
    ppc64le:
    - cdrdao

  labels:
  - eln
  - c9s
