document: feedback-pipeline-workload
version: 1
data:
  name: Ruby runtime
  description: Ruby interpretter and the most basic libraries
  maintainer: sst_cs_apps

  packages:
  - ruby
  - ruby-default-gems
  - ruby-devel
  - ruby-libs
  - rubygem-bigdecimal
  - rubygem-bundler
  - rubygem-io-console
  - rubygem-irb
  - rubygem-json
  - rubygem-minitest
  - rubygem-power_assert
  - rubygem-psych
  - rubygem-rake
  - rubygem-rbs
  - rubygem-rdoc
  - rubygem-rexml
  - rubygem-rss
  - rubygem-test-unit
  - rubygem-typeprof
  - rubygems
  - rubygems-devel
  - rubygem-abrt

  labels:
  - eln
  - c9s

  package_placeholders:
    rubygem-tilt:
      srpm: rubygem-tilt
      description: Generic interface to multiple Ruby template engines
# asamalik: These must be package names. We need to get these fixed
#      requires:
#        - ruby(rubygems)
#
#      buildrequires:
#        - rubygem(minitest)
#        - /usr/bin/ronn
