document: feedback-pipeline-workload
version: 1
data:
  name: Apache Maven 3.6
  description: Java project management and project comprehension tool
  maintainer: sst_cs_apps

  modules_enable:
  - maven:3.6

  packages:
  - maven

  labels:
  - eln
